apiVersion: v1
kind: Pod
metadata:
  labels:
    run: zone-pod
  name: zone-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1a
  containers:
  - image: nginx
    name: zone-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

