apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fast-pod
  name: fast-pod
spec:
  volumes:
  - name: fast-volume
    persistentVolumeClaim:
      claimName: fast-pvc
  containers:
  - image: busybox:1.36.1
    name: fast-pod
    resources: {}
    volumeMounts:
      - name: fast-volume
        mountPath: /data/
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

