apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web
  name: business-app
spec:
  volumes:
    - name: configdir
      emptyDir: {}
  initContainers:
    - image: busybox:1.36.1
      name: configurer
      command: ["sh", "-c", "echo Configuring Application ... && \
                 mkdir -p /usr/shared/app && echo -e '{\"dbConfig\": \
                 {\"host\":\"localhost\", \"port\":5432, \"dbName\": \"customers                 \"}}' > /usr/shared/app/config.json"]
      volumeMounts:
        - name: configdir
          mountPath: "/usr/shared/app"
  containers:
  - image: busybox:1.36.1
    name: web
    ports:
     - containerPort: 8080
    volumeMounts:
     - name: configdir
       mountPath: "/usr/shared/app"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
