apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: neb-new-job
  namespace: neptune
spec:
  parallelism: 2
  completion: 3
  template:
    metadata:
      creationTimestamp: null
      labels:
        id: awesome-job
    spec:
      containers:
      - image: busybox:1.31.0
        name: neb-new-job-container
        resources: {}
      command: ["sh", "-c", "sleep 2 && echo done"]
      restartPolicy: Never
status: {}
