apiVersion: v1
kind: LimitRange
metadata:
  name: resource-constraint
  namespace: k97
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 200m
    default:
      cpu: 200m
    min:
      cpu: 100m
    max:
      cpu: "2"

