apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2025-04-19T18:15:58Z"
  generation: 1
  name: looper-cron
  namespace: default
  resourceVersion: "386845"
  uid: dbba64ab-8155-42dd-b667-a36dca86fbc9
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: looper-cron
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: busybox:1.36.1
            imagePullPolicy: IfNotPresent
            name: looper-cron
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}
