apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: business-app
  name: business-app
spec:
  volumes:
  - name: logs-volume
    emptyDir: {}
  containers:
  - image: nginx:1.25.1
    name: business-app
    resources: {}
    volumeMounts:
    - mountPath: /var/log/nginx
      name: logs-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
