apiVersion: v1
kind: Pod
metadata:
  name: pod-tolerations
spec:
  tolerations:
  - key: "key1"
    operator: "Equal" 
    value: "value1"
    effect: "NoSchedule"
  containers:
  - image: busybox
    name: pod-tolerations-container

    
