apiVersion: v1
kind: Pod
metadata:
  name: rate-limiter
spec:
  containers:
  - image: bmuschko/nodejs-business-app:1.0.0
    name: business-app
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: "256Mi"
        cpu: "1"
      requests:
        memory: "128Mi"
        cpu: "500m"
  - image: bmuschko/nodejs-ambassador:1.0.0
    name: ambassador
    ports:
    - containerPort: 8081
    resources:
      limits:
        memory: "641Mi"
        cpu: "1"
      requests:
        memory: "200Mi"
        cpu: "500m"

