apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 40%
      maxSurge: 10%
    minReadySeconds: 60
    selector:
      matchLabels:
        app: httpd
    template:
      metadata:
        name: httpd
      spec:
        containers:
          - name: httpd
            image: httpd:2.4.23-alpine
            ports:
              - containerPort: 80
                protocol: TCP
            readinessProbe:
              httpGet:
                path: /
                port: 80

