apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
    - name: nginx
      image: nginx:1.25.1
      volumeMounts:
        - name: logs-vol
          mountPath: /var/logs/nginx
    - name: sidecar
      image: busybox:1.36.1
      command: ["sh", "-c", "while true; do if [ \"$(cat /var/log/nginx/error.log | grep 'error')\" != \"\" ]; then echo 'Error discovered!'; fi'; sleep 10; done"]
      volumeMounts:
        - name: logs-vol
          mountPath: /var/log/nginx

  volumes:
    - name: logs-vol
      emptyDir: {}

