apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
spec:
  containers:
  - image: nginx:1.25.1
    name: hello-word
    ports:
    - name: nginx-port
      containerPort: 80
    startupProbe:
      tcpSocket:
        port: nginx-port
    readinessProbe:
      httpGet:
        path: /
        port: nginx-port
      initialDelaySeconds: 2
      periodSeconds: 8

