apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: config-app
  name: config-app
spec:
  containers:
  - image: busybox
    name: config-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
