apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  volumes:
    name: shared-data
    emptyDir: {}
  initContainers:
  - name: init
    image: busybox
    command: ['sh', '-c', 'echo "Hello CKAD" > /data/message.txt']
    volumeMounts:
    - name: shared-data
      mountPath: /data
  containers:
  - image: busybox
    name: main
    command: ['sh', '-c', 'cat /data/message.txt && sleep 3600']
    volumeMounts:
    - name: shared-data
      mountPath: /data

