apiVersion: v1
kind: Pod
metadata:
  name: multi-log
spec:
  containers:
  - name: logger
    image: busybox
    command: ['sh, '-c', 'while true; do date >> /shared/log.txt; sleep 5; done']
  - name: viewer
    image: busybox
    command: ['sh', '-c', 'sleep 3600']

